name: Dummy

on:
  workflow_dispatch:

jobs:
  dummy:
    name: Dev and Debug Workflows

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.1
          opam-repositories: |
            pin: git+https://github.com/ocaml/opam-repository#15b381eeae

      - run: git rev-parse HEAD
